name: Cost & Risk Analysis (Terraform + CloudFormation)

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  tfx-terraform:
    name: Terraform plan analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run tfx
        uses: amtago/infra-cost-risk-adviser@main
        with:
          plan-file:        plan.json
          region:           us-east-1
          github-token:     ${{ secrets.GITHUB_TOKEN }}
          comment-on-pr:    'true'
          fail-on-critical: 'false'

  tfx-cfn:
    name: CloudFormation change set analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run tfx (CFN)
        uses: amtago/infra-cost-risk-adviser@main
        with:
          cfn-changeset-file: cfn_changeset.json
          cfn-template-file:  cfn_template.json
          region:             us-east-1
          github-token:       ${{ secrets.GITHUB_TOKEN }}
          comment-on-pr:      'true'
          fail-on-critical:   'false'
